runtime: python39
entrypoint: gunicorn -b :8000 main:app

env_variables:
  SECRET_KEY: 75b31130a8bac4064e024302fa4b5812b63cbd97de90c1915590032212f2e0bd
  DATABASE_URI: mongodb+srv://goFood:goFoodOwner@cluster0.s05gfyt.mongodb.net/communityConnect?retryWrites=true&w=majority

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
