export const BASE_URL=process.env.REACT_APP_API_BASE_URL
export const INTERNAL_SERVER_ERROR_MESSAGE = process.env.REACT_APP_INTERNAL_SERVER_ERROR_MESSAGE;
export const SERVER_DOWN_MESSAGE = process.env.REACT_APP_SERVER_DOWN_MESSAGE;
